import type { CardData } from './types';

const artwork = (number: number) =>
  `${import.meta.env.BASE_URL}artworks/artwork-${String(number).padStart(2, '0')}.svg`;

export const cards: CardData[] = [
  {
    id: 1,
    title: 'Quiet Signal',
    category: 'text',
    description: 'A small phrase that gives a noisy day room to breathe.',
    image: artwork(1),
    presentation: 'framed',
    position: { x: 80, y: 100, width: 132, height: 132, rotation: 0 },
  },
  {
    id: 2,
    title: 'Field Notes',
    category: 'artwork',
    description: 'Observations gathered slowly, with attention to what usually passes by.',
    image: artwork(2),
    presentation: 'image',
    position: { x: 260, y: 45, width: 166, height: 126, rotation: -2.5 },
  },
  {
    id: 3,
    title: 'Soft Focus',
    category: 'sketch',
    description: 'A reminder that not every detail needs to be sharp to be remembered.',
    image: artwork(3),
    presentation: 'framed',
    position: { x: 505, y: 132, width: 120, height: 120, rotation: 1.8 },
  },
  {
    id: 4,
    title: 'Open Window',
    category: 'symbol',
    description: 'A line between the familiar room and the wider world outside.',
    image: artwork(4),
    presentation: 'image',
    position: { x: 735, y: 75, width: 118, height: 155, rotation: 2.2 },
  },
  {
    id: 5,
    title: 'Still Here',
    category: 'text',
    description: 'A note on presence: simple, quiet, and enough for now.',
    image: artwork(5),
    presentation: 'framed',
    position: { x: 985, y: 130, width: 146, height: 146, rotation: -1.5 },
  },
  {
    id: 6,
    title: 'Blue Hour',
    category: 'artwork',
    description: 'The last cool light resting on rooftops just before evening settles in.',
    image: artwork(6),
    presentation: 'image',
    position: { x: 1190, y: 72, width: 150, height: 112, rotation: 1.1 },
  },
  {
    id: 7,
    title: 'After Rain',
    category: 'sketch',
    description: 'Reflections turn an ordinary street into a second, brighter landscape.',
    image: artwork(7),
    presentation: 'framed',
    position: { x: 110, y: 325, width: 138, height: 138, rotation: -1.3 },
  },
  {
    id: 8,
    title: 'Tidal Memory',
    category: 'symbol',
    description: 'An abstract study of the marks water leaves behind as it recedes.',
    image: artwork(8),
    presentation: 'image',
    position: { x: 340, y: 300, width: 123, height: 166, rotation: 1.4 },
  },
  {
    id: 9,
    title: 'Warm Distance',
    category: 'text',
    description: 'Layered tones hold the feeling of a faraway place in late sunlight.',
    image: artwork(9),
    presentation: 'framed',
    position: { x: 535, y: 330, width: 118, height: 118, rotation: 0.8 },
  },
  {
    id: 10,
    title: 'Small Orbit',
    category: 'artwork',
    description: 'A composition about the little worlds that form around everyday rituals.',
    image: artwork(10),
    presentation: 'image',
    position: { x: 745, y: 282, width: 182, height: 136, rotation: -1.8 },
  },
  {
    id: 11,
    title: 'First Pass',
    category: 'sketch',
    description: 'The first loose marks that make a new idea feel possible.',
    image: artwork(11),
    presentation: 'framed',
    position: { x: 970, y: 350, width: 128, height: 128, rotation: 1.7 },
  },
  {
    id: 12,
    title: 'Found Shape',
    category: 'symbol',
    description: 'A quick outline traced from a shape noticed in the landscape.',
    image: artwork(12),
    presentation: 'image',
    position: { x: 1165, y: 302, width: 144, height: 166, rotation: 1.2 },
  },
  {
    id: 13,
    title: 'Contour Walk',
    category: 'text',
    description: 'One continuous line follows a path through an imagined hillside.',
    image: artwork(13),
    presentation: 'image',
    position: { x: 60, y: 575, width: 170, height: 130, rotation: -2.1 },
  },
  {
    id: 14,
    title: 'Paper Garden',
    category: 'artwork',
    description: 'A collection of botanical gestures, left open and unfinished.',
    image: artwork(14),
    presentation: 'framed',
    position: { x: 300, y: 600, width: 132, height: 132, rotation: 1.1 },
  },
  {
    id: 15,
    title: 'Loose Thread',
    category: 'sketch',
    description: 'A wandering study that connects fragments without forcing an answer.',
    image: artwork(15),
    presentation: 'image',
    position: { x: 525, y: 555, width: 122, height: 164, rotation: -1.4 },
  },
  {
    id: 16,
    title: 'North Mark',
    category: 'symbol',
    description: 'A simple mark for finding direction when the map is incomplete.',
    image: artwork(16),
    presentation: 'framed',
    position: { x: 745, y: 630, width: 116, height: 116, rotation: 1.6 },
  },
  {
    id: 17,
    title: 'Common Ground',
    category: 'text',
    description: 'Two forms meet at the center, making a place they can both share.',
    image: artwork(17),
    presentation: 'image',
    position: { x: 950, y: 570, width: 180, height: 138, rotation: 1.5 },
  },
  {
    id: 18,
    title: 'Open Circle',
    category: 'artwork',
    description: 'An unclosed loop that leaves space for whatever comes next.',
    image: artwork(18),
    presentation: 'framed',
    position: { x: 1190, y: 630, width: 140, height: 140, rotation: -1.1 },
  },
  {
    id: 19,
    title: 'Day Marker',
    category: 'sketch',
    description: 'A quiet emblem for the small rituals that shape a day.',
    image: artwork(19),
    presentation: 'framed',
    position: { x: 260, y: 855, width: 124, height: 124, rotation: -1.8 },
  },
  {
    id: 20,
    title: 'New Growth',
    category: 'symbol',
    description: 'A sign of renewal drawn from the first green appearing after winter.',
    image: artwork(20),
    presentation: 'image',
    position: { x: 900, y: 860, width: 176, height: 132, rotation: 1.3 },
  },
];
